Fixed undefined reference to sysctl_sched_tick_max_deferment caused when CONFIG_NO_HZ_FULL not selected
Signed-off-by: Gary S. Robertson <gary.robertson@linaro.org>